### ISSUE TITLE
Cannot run on Windows

### ISSUE THREAD

**Issue by HaradaKumiko** [adibmuhamad/ekyc#1]
my machine use go version go1.22.2 windows/amd64

![image](https://github.com/adibmuhamad/ekyc/assets/42530587/fa8db2e3-2204-411d-a5df-d43d57eb319c)

**Comment by adibmuhamad** [comment]
Sorry for late response, I think the problem is not having OpenCV correctly installed in your machine, or not having the matching version. Maybe you could try following the steps in this [link](https://gocv.io/getting-started/windows/).
